language: python
python:
  - "3.7"
script:
  - cd tests ; pytest
before_deploy:
  - cd ..
deploy:
  provider: heroku
  api_key:
    secure: "t/i89KJp3LxlOuxnqJkeAUjKOTFDadZGMTAeA55wpWHV6YIgs4rMXxtkvDUO+o2AMpkDyxOu8wImbTeG22ZM83RKea/Pn+ILDRBWnUenzC1B1tHWfMUGVjmmG3K51bGGX3q3FNVUvWYrDnwqJaNmnwUr1hJHZv7AL85j4+oM1QWfNFS4BwKUC9RYVtgVKrUmYrtIqTh6FqgrMWbjc77LIuQlm3Bu6uf3g4IP2rKg13RDv0hDzecP4c5pSujY+jFDTEPY8Xq7NyKbD3LZ2mf6FAdKxvPnxejijulS3U1c13xAHgM/TYs7Sh0l+FQ0iMXiQrd4uiGtAPnAJ8PqR8a9rsczHhO3CwQPsZ8d4QVmWNxQBBPKSvI81tuBjo+MssPNiH/vIJ3GymY2Kx/UGAs5AO+taosDXOlHmqdHriqq4pYoCo25RIqBE31DQ7Zi9e79okcXUl8y752LjTwsZpN3AOjRAij+nY3wHQK6fLJv1fvus70c57cWUiwQLCC4hmcqzaIXqlUS39wqIK5JjiT/1Q1xs5YKYgKHymSHTRT9fOQBL2aa76AgQNhXNOufs9XQajvhSpcmG4N/IHMqH/GURiUY/cdkNwTGtDQyK20Ls6jlAPPKATak5E1ScqlRAUyl0LObK4tHYn1Oi4cQ7skEgmAna3Uwhns6XI2U45xEOew="
  app: resume-depo