language: python
python:
  - "3.7"
before_install:
    - apt-get update
    - apt-get install dos2unix
install:
  - pip install -r requirements.txt
before_script:
    - dos2unix ./bin/docker_gunicorn_start.sh
    - chmod +x ./bin/docker_gunicorn_start.sh
script:
  - ./bin/docker_gunicorn_start.sh
  - sleep 5
  - cd tests ; pytest