language: python
python:
- '3.7'
script:
- cd tests ; pytest -v test_index.py
before_deploy:
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: MiRGPgS2G/Zvso3XdFnAvMIRrWjh2iVWnVpOCx80rm3KJNLnmRiyIVyppZwAEcCUHcE8RHadxj0mRC9MkdH6jxJLr/1Z0wIOWJfNbJoHiK2WlDhb0v95Yyyy/htSPS49ySeT9TBrSHkSBGO1ShAB8/1JurBntPgbo3sX2rLwNXwglq51oMkN9BZQsXTfLBlQ3o48rd4YgPj3FAGWZ3naOUUWaELheXXReLs02NvY30xu1tP7ZwzOR2LNZXSPpjRk+vUb4WIkR0koYHx3mWAn6u3hrYK4yzjkTUcpUPnB2WIjNI9EwMfqN4FqELzgENjuc12VR3GSWoD2gO9zYPWYLAakuBc6pT0Wz+9/HivugQsFsULjqf+7TPdtDY3eQMpxrNAC8IB5vssWyUdQGvaNa5SJWWuNXCgbhyP+WLlrOarQtgnSygXaagL384UuSeQ4+WYrPE4AMh9kfaZygYMq2gvHx51u97BDZVlg2LGrVUZfxjPpAkrGBsKBNABPW2cjEpoVxiSjijGxDQMNX5iHVuJBao6U9PYRF+oOh+7H1r3csymQungzXb8m3cob1F2BP4hxE942Abl879zQSeOpjW3le86lrrGmhfxCXgxtBf9pGsIaC3Xf+fPSIywDYpcjMj6VIBD4LlkfKs5U0EHB3yjl7kWTBFaiQXWuYJjo4QM=
  app: resume-depo
