language: python
python:
- '3.7'
script:
- cd tests ; pytest -v test_index.py
before_deploy:
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: "OJHP4IoaRaduoa3LzXo5dopL3uORvEDUKqEk22Bs4pAwitQpigIvwbF7DZZr802CfYc7I/HN8n7bgPthQbtf+udUapf/gNDfGiWFENADM5mXG+8AnGwoTmmj5mdklSooWBHlBFEQV27En2A6+8TAkMYnYvsNb8kPJyoCE4fXm6sVq33NC3l6SljVlkH5chUtqm/P190WwLh/ehCOrqsnGlVisGnH/4RfJSnjzoT/alQ/hE5GPkN1GbWK38V2OWNt5Y8Q3jYJ6965LM3NQr2z9Aas7HvMVDwi+0s+FSclA1Brl89RaO93Fgn3VwqeG2S+Jd/kSbfVORf4+CZwO8nFPJo2wfjX11i6bVrCEU/kiLovBJoPPCB7v21TZ6GCGMlcJJ1ENKjornvac90SlonU1VWGKrFQVwDWYHjQbIIJIuf5GnHIVPAj5IYRhuQEAM0gGX0VTmdnwR0LDMc+W9puLLpap4MhKOkrRxSyWt9MEOihcoqMZwqTp3H3fEfXaXB3Qd9U7sDUzO8OrbsckNNzsQt/b5FBROy9OFkM6Ko2q445aafqdmlpE3mhFDkBPM1ypg07Ea5fa9mI4gNIerBbDBuCkmu6OiQP3S901KH12WmqbQyGU4UFViQEo69RDjoun7lJxLgftHrx/8oPxksX9T4PcFgLhfzsN8TQ4bAS7Ro="
  app: resume-depo
