language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install dos2unix
install:
  - pip install -r requirements.txt
before_script:
  - dos2unix ./bin/docker_gunicorn_start.sh
  - chmod +x ./bin/docker_gunicorn_start.sh
  - git add .
  - git commit -m "created repo from travis to heroku"
script:
  - ./bin/docker_gunicorn_start.sh daemon
  - sleep 5
  - cd tests ; pytest
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: resume-depo