language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - sudo chmod 755 ./bin/docker_gunicorn_start.sh
script:
  - ./bin/docker_gunicorn_start.sh
  - sleep 5
  - cd tests ; pytest