apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-website-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resume-website-svc
            port:
              number: 80