apiVersion: v1
kind: Pod
metadata:
  name: resume-website
spec:
  containers:
  - name: resume-website
    imagePullPolicy: Always
    image: ghcr.io/depontimatteo/resume-website:latest
    env:
    - name: PORT
      value: "5000"
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
