apiVersion: v1
kind: Service
metadata:
  labels:
    app: resume-website
  name: resume-website
  namespace: resume-depo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: resume-website
  type: LoadBalancer