apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-website
  labels:
    app: resume-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-website
  template:
    metadata:
      labels:
        app: resume-website
    spec:
      containers:
      - name: resume-website
        imagePullPolicy: Always
        image: ghcr.io/depontimatteo/resume-website:latest
        env:
        - name: PORT
          value: "5000"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

